build:
  image: teaci/msys$$arch
  shell: mingw$$arch
  pull: true
  commands:
    - cmd /c ver
    - cmd /c "c:/msys64/mingw64/bin/gcc.exe"
    - ./test_cmd.sh
    - cmd /c c:/msys64/mingw64/bin/gcc.exe

matrix:
  arch:
    - 64
