build:
  image: teaci/msys$$arch
  shell: mingw$$arch
  pull: true
  environement:
    - foo=bar
  commands:
    - foo2=bar2
    - echo a && echo b
    - echo $foo
    - echo "$foo"
    - echo $foo2

matrix:
  arch:
    - 64
